version: '3.3'

services:
#zookeeper:
#  image: wurstmeister/zookeeper
#  expose:
#    - 2181
#  ports:
#    - "2181:2181"
#
#kafka:
#  image: wurstmeister/kafka:0.9.0.1
#  expose:
#    - 9092
#  ports:
#    - "9092:9092"
#  links:
#    - zookeeper:zk
#  environment:
#    KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
#  volumes:
#    - /var/run/docker.sock:/var/run/docker.sock

  cassandra:
    image: cassandra
    restart: always
    expose:
      - "7000"
      - "7001"
      - "7199"
      - "9042"
      - "9160"
    ports:
      - "9160:9160"
      - "9042:9042"

  fenix1:
    image: docker-registry.prod.williamhill.plc/martin.hatas/fenix:1.0.0-SNAPSHOT
    restart: always
    expose:
      - "2551"
    ports:
      - "7777:7777"
    environment:
      - CASSANDRA=cassandra
      - KAFKA=127.0.0.1
    links:
      - cassandra
  #    - kafka

  fenix2:
    image: docker-registry.prod.williamhill.plc/martin.hatas/fenix:1.0.0-SNAPSHOT
    restart: always
    expose:
      - "2551"
      - "7777"
    environment:
      - CASSANDRA=cassandra
      - KAFKA=127.0.0.1
    links:
      - cassandra
  #    - kafka

  fenix3:
    image: docker-registry.prod.williamhill.plc/martin.hatas/fenix:1.0.0-SNAPSHOT
    restart: always
    expose:
      - "2551"
      - "7777"
    environment:
      - CASSANDRA=cassandra
      - KAFKA=127.0.0.1
    links:
      - cassandra
  #    - kafka

# haproxy:
#   image: haproxy:latest
#   restart: always
#   ports:
#     - "80:80"
#   volumes:
#     - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
#   links:
#     - fenix
